language: python
python:
- '3.6'
before_install:
- openssl aes-256-cbc -K $encrypted_cb887607c220_key -iv $encrypted_cb887607c220_iv
  -in t_key.json.enc -out t_key.json -d

install:
- pip install -r requirements.txt
script:
- echo "Hello world"
deploy:
  provider: gae
  keyfile: "./deploy/t_key.json"
  project: flynn-labs
  on: master
  edge: true
