language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- echo "Hello world"
deploy:
  provider: gae
  keyfile: flynn-labs-b4dc0d737627.json.enc
  project: flynn-labs
  on: master
  edge: true
before_install:
- openssl aes-256-cbc -K $encrypted_cb887607c220_key -iv $encrypted_cb887607c220_iv
  -in flynn-labs-b4dc0d737627.json.enc -out flynn-labs-b4dc0d737627.json -d
