#env: standard
runtime: nodejs10
#service: default

handlers:
  - url: /(.*\.(ico|js))$
    static_files: dist/\1
    upload: dist/.*\.(ico|js)$

  - url: .*
    static_files: dist/index.html
    upload: dist/index.html
