runtime: nodejs10

handlers:
  - url: /(.*\.(ico|js|json))$
    static_files: build/\1
    upload: build/.*\.(ico|js|json)$

  - url: .*
    static_files: build/index.html
    upload: build/index.html
