runtime: custom
env: flex

handlers:
  - url: /ncaa_api/.*
    script: auto

  - url: /(.*\.(ico|js))$
    static_files: dist/\1
    upload: dist/.*\.(ico|js)$

  - url: .*
    static_files: dist/index.html
    upload: dist/index.html
