env: standard
runtime: nodejs10
service: default

handlers:
  - url: /public
    static_dir: public

  - url: /(.*\.(json|ico|js))$
    static_files: dist/\1
    upload: dist/.*\.(json|ico|js)$

  - url: .*
    static_files: dist/index.html
    upload: dist/index.html
