name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Publish app to Google App Engine
      uses: zxyle/publish-gae-action@v2.2
      with:
        # The service account email which will be used for authentication.
        service_account_email: flynn-labs@appspot.gserviceaccount.com
        # The service account key which will be used for authentication.
        service_account_key: secret.GAE_SERVICE_KEY
        # GAE project id
        project_id: flynn-labs
        # GAE variables to be written to the app.yaml file
        #gae_variables: # optional
