name: Node.js Build and Test

on:
  push:
    branches-ignore:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
        
    steps:
      - uses: ros-tooling/setup-ros@0.0.14
        with: 
          required-ros-distributions: eloquent
      - run: "source /opt/ros/dashing/setup.bash"
      - uses: actions/checkout@v2
      - name: install and build Node.js
        uses: actions/setup-node@v1
          with:
            node-version: '10.x'
      - run: npm install
      - run: npm run build --if-present
      # - run: npm test
        env:
          CI: true
