name: Node.js Build and Test

on:
  push:
    branches-ignore:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup ROS2
        uses: ros-tooling/setup-ros@0.0.11
        with:
          required-ros-distributions: eloquent
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with: 
          node-version: '10.x'
      - run: source /opt/ros/eloquent/setup.bash && npm install && npm run build --if-present
      # - run: npm test
