name: Node.js Build and Test

on:
  push:
    branches-ignore:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: ros-tooling/setup-ros@0.0.11
        with:
          required-ros-distributions: eloquent
      - run: "source /opt/ros/eloquent/setup.bash"
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install and Build package
        uses: actions/setup-node@v1
        with: 
          node-version: '10.x'
      - run: npm install
      - run: npm run build --if-present
      # - run: npm test
        env:
          CI: true
