name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
        
    steps:
    - name: install and build
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build --if-present
    - run: npm test
      env:
        CI: true
    
    
    #  with:
        # The service account email which will be used for authentication.
     #   service_account_email: flynn-labs@appspot.gserviceaccount.com
        # The service account key which will be used for authentication.
      #  service_account_key: secret.GAE_SERVICE_KEY
        # GAE project id
       # project_id: flynn-labs
        # GAE variables to be written to the app.yaml file
        #gae_variables: # optional
