name: Node.js GAE Build, Test and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
        
    steps:
    - uses: actions/checkout@v2
    - name: install and build Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '11.x'
    - run: npm install
    - run: npm run build --if-present
   # - run: npm test
      env:
        CI: true
    - uses: actions-hub/gcloud@271.0.0
      env:
        PROJECT_ID: ${{ secrets.GCLOUD_PROJECT_ID }}
        APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      with:
        args: app deploy app.yaml
